databases:
  - name: fraud-detection-db
    databaseName: fraud_detection_db
    user: fraud_detection_user
    region: oregon

services:
  - type: web
    name: fraud-detection-app
    runtime: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn insurance_fraud_detection.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fraud-detection-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: insurance_fraud_detection.settings_production
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: WEB_CONCURRENCY
        value: 4